import { render,screen,waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { describe,expect,it,vi } from "vitest";
import { bookingTranslations,BOOKING_ERROR_CODES } from "./publicBookingI18n";
import { I18nProvider } from "./i18n";
import { WebsiteConfigProvider } from "./websiteConfig";
import { BookingContactForm } from "@/components/booking/BookingContactForm";
const langs=["de","en","tr","ru","ar","it","zh","hi","es","fr","nl","pl"];
describe("booking translations",()=>{
 it("contains every non-empty key and backend error in all twelve languages",()=>{expect(Object.keys(bookingTranslations)).toEqual(langs);const expected=Object.keys(bookingTranslations.de);for(const lang of langs){expect(Object.keys(bookingTranslations[lang])).toEqual(expected);for(const value of Object.values(bookingTranslations[lang]))expect(value.trim()).not.toBe("");for(const code of BOOKING_ERROR_CODES)expect(bookingTranslations[lang][`error_${code}`]).toBeTruthy();}});
 it("provides the selected date label in all twelve languages",()=>{const expected={de:"Ausgewähltes Datum",en:"Selected date",tr:"Seçilen tarih",ru:"Выбранная дата",ar:"التاريخ المحدد",it:"Data selezionata",zh:"已选日期",hi:"चुनी गई तारीख",es:"Fecha seleccionada",fr:"Date sélectionnée",nl:"Geselecteerde datum",pl:"Wybrana data"};for(const lang of langs)expect(bookingTranslations[lang].selectedDate).toBe(expected[lang as keyof typeof expected]);});
 it("has localized free messaging and exactly one consent placeholder",()=>{for(const lang of langs){expect(bookingTranslations[lang].costNote).toBeTruthy();expect(bookingTranslations[lang].book).toBeTruthy();expect(bookingTranslations[lang].consent.match(/\{privacyLink\}/g)).toHaveLength(1);}expect(bookingTranslations.de.costNote).toBe("Kostenfreier Rückruf · ca. 15 Minuten");expect(bookingTranslations.de.book).toBe("Kostenfreien Rückruf buchen");expect(bookingTranslations.de.success).toBe("Vielen Dank! Dein Rückruf wurde erfolgreich gebucht.");});
 it("does not reuse German translations as fallbacks",()=>{for(const lang of langs.slice(1)){expect(bookingTranslations[lang]).not.toBe(bookingTranslations.de);for(const key of ["costNote","book","success","consent","privacyLink"] as const)expect(bookingTranslations[lang][key]).not.toBe(bookingTranslations.de[key]);}});
 it.each([["de","Datenschutzerklärung"],["en","Privacy policy"],["tr","Gizlilik politikası"],["ar","سياسة الخصوصية"]])("renders one localized privacy link inside the consent sentence for %s",async(lang,label)=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response("[]",{status:200}));render(<MemoryRouter initialEntries={[`/?lang=${lang}`]}><WebsiteConfigProvider><I18nProvider><BookingContactForm value={{salutation:"",first_name:"",last_name:"",email:"",phone:"",note:"",consent:false,honeypot:""}} onChange={()=>{}} onSubmit={()=>{}} submitting={false} errors={{}} b={bookingTranslations[lang]} privacyPath={`/datenschutz?lang=${lang}`} onBack={()=>{}}/></I18nProvider></WebsiteConfigProvider></MemoryRouter>);const links=screen.getAllByRole("link",{name:new RegExp(label)});expect(links).toHaveLength(1);expect(links[0]).toHaveAttribute("href",`/datenschutz?lang=${lang}`);expect(links[0]).toHaveAttribute("target","_blank");expect(links[0]).toHaveAttribute("rel","noopener noreferrer");if(lang==="de")expect(screen.getByText(/Ich stimme der Verarbeitung/)).toHaveTextContent(/Ich stimme der Verarbeitung meiner Daten zur Rückrufbuchung gemäß der Datenschutzerklärung.*zu\./);if(lang==="ar")await waitFor(()=>expect(document.documentElement.dir).toBe("rtl"));});
});
