import { useI18n } from "./i18n";

const de = {
 title:"Rückruf buchen", description:"Wähle einen passenden Termin. Wir rufen dich zur ausgewählten Zeit zurück.", date:"Datum auswählen", time:"Uhrzeit auswählen", contact:"Kontaktdaten", loading:"Freie Termine werden geladen …", empty:"In diesem Zeitraum sind keine freien Termine verfügbar.", retry:"Erneut versuchen", back:"Zurück", continue:"Weiter", salutation:"Anrede", mr:"Herr", ms:"Frau", diverse:"Divers", first:"Vorname", last:"Nachname", email:"E-Mail", phone:"Telefonnummer", note:"Notiz (optional)", consent:"Ich habe die Datenschutzerklärung gelesen und stimme der Verarbeitung meiner Daten zur Rückrufbuchung zu.", required:"Bitte fülle dieses Pflichtfeld aus.", invalidEmail:"Bitte gib eine gültige E-Mail-Adresse ein.", invalidPhone:"Bitte gib eine gültige Telefonnummer ein.", book:"Rückruf verbindlich buchen", summary:"Dein Termin", success:"Dein Rückruf ist gebucht", successBody:"Wir rufen dich zum gewählten Termin an.", home:"Zurück zur Website", duration:"Dauer", minutes:"Minuten", status:"Status", calendar:"Kalender", config:"Die Terminbuchung ist derzeit nicht korrekt konfiguriert.", generic:"Die Anfrage konnte nicht verarbeitet werden. Bitte versuche es erneut.", unavailable:"Dieser Termin wurde inzwischen vergeben. Bitte wähle einen neuen Termin.", disabled:"Die Online-Buchung ist derzeit nicht verfügbar.", rate:"Zu viele Anfragen. Bitte versuche es später erneut.", consentError:"Bitte bestätige die Datenschutzerklärung.", selectSlot:"Bitte wähle zuerst einen Termin.", booked:"Gebucht"
};
type Texts = typeof de;
const translations: Record<string, Texts> = {
 de,
 en:{...de,title:"Book a callback",description:"Choose a convenient time. We will call you back then.",date:"Choose date",time:"Choose time",contact:"Contact details",loading:"Loading available appointments …",empty:"No appointments are available in this period.",retry:"Try again",back:"Back",continue:"Continue",salutation:"Title",mr:"Mr",ms:"Ms",diverse:"Other",first:"First name",last:"Last name",email:"Email",phone:"Phone number",note:"Note (optional)",consent:"I have read the privacy policy and consent to my data being processed for this callback.",required:"Please complete this required field.",invalidEmail:"Enter a valid email address.",invalidPhone:"Enter a valid phone number.",book:"Book callback",summary:"Your appointment",success:"Your callback is booked",successBody:"We will call you at the selected time.",home:"Back to website",duration:"Duration",minutes:"minutes",status:"Status",calendar:"Calendar",config:"Appointment booking is not configured correctly at present.",generic:"We could not process the request. Please try again.",unavailable:"This appointment has just been taken. Please choose another.",disabled:"Online booking is currently unavailable.",rate:"Too many requests. Please try again later.",consentError:"Please accept the privacy policy.",selectSlot:"Please select an appointment first.",booked:"Booked"},
 tr:{...de,title:"Geri arama randevusu al",description:"Uygun bir saat seçin. Seçtiğiniz saatte sizi arayacağız.",date:"Tarih seçin",time:"Saat seçin",contact:"İletişim bilgileri",book:"Geri aramayı ayırt",success:"Geri arama randevunuz alındı"},
 ru:{...de,title:"Записаться на обратный звонок",description:"Выберите удобное время, и мы вам перезвоним.",date:"Выберите дату",time:"Выберите время",contact:"Контактные данные",book:"Записаться на звонок",success:"Обратный звонок забронирован"},
 ar:{...de,title:"حجز مكالمة",description:"اختر موعدًا مناسبًا وسنتصل بك في الوقت المحدد.",date:"اختر التاريخ",time:"اختر الوقت",contact:"بيانات الاتصال",book:"تأكيد حجز المكالمة",success:"تم حجز مكالمتك"},
 it:{...de,title:"Prenota una richiamata",description:"Scegli un orario adatto. Ti chiameremo all'ora selezionata.",date:"Scegli la data",time:"Scegli l'orario",contact:"Dati di contatto",book:"Prenota richiamata",success:"Richiamata prenotata"},
 zh:{...de,title:"预约回电",description:"请选择合适的时间，我们会按时致电给您。",date:"选择日期",time:"选择时间",contact:"联系信息",book:"确认预约回电",success:"回电已预约"},
 hi:{...de,title:"वापसी कॉल बुक करें",description:"सुविधाजनक समय चुनें। हम चुने हुए समय पर आपको कॉल करेंगे।",date:"तारीख चुनें",time:"समय चुनें",contact:"संपर्क विवरण",book:"वापसी कॉल बुक करें",success:"आपकी कॉल बुक हो गई है"},
 es:{...de,title:"Reservar una llamada",description:"Elige un horario conveniente. Te llamaremos a la hora seleccionada.",date:"Elegir fecha",time:"Elegir hora",contact:"Datos de contacto",book:"Reservar llamada",success:"Tu llamada está reservada"},
 fr:{...de,title:"Réserver un rappel",description:"Choisissez un créneau. Nous vous rappellerons à l’heure sélectionnée.",date:"Choisir la date",time:"Choisir l’heure",contact:"Coordonnées",book:"Réserver le rappel",success:"Votre rappel est réservé"},
 nl:{...de,title:"Terugbelafspraak boeken",description:"Kies een geschikt tijdstip. We bellen je dan terug.",date:"Datum kiezen",time:"Tijd kiezen",contact:"Contactgegevens",book:"Terugbelafspraak boeken",success:"Je terugbelafspraak is geboekt"},
 pl:{...de,title:"Umów rozmowę telefoniczną",description:"Wybierz dogodny termin. Oddzwonimy o wybranej porze.",date:"Wybierz datę",time:"Wybierz godzinę",contact:"Dane kontaktowe",book:"Umów rozmowę",success:"Rozmowa została umówiona"},
};
export const useBookingI18n = () => { const { lang } = useI18n(); return { b: translations[lang] || de, lang }; };

