export const tariffCallbackTranslations: Record<string,Record<string,string>> = {
  de:{tariff_callback_title:"Noch Fragen zu deiner Tarifempfehlung?",tariff_callback_subtitle:"Wir beantworten deine Fragen persönlich und erklären dir deine Empfehlung verständlich.",tariff_callback_button:"Rückruf buchen",tariff_callback_avatar_alt:"Persönliche Beratung zu deiner Tarifempfehlung"},
  en:{tariff_callback_title:"Any questions about your tariff recommendation?",tariff_callback_subtitle:"We’ll answer your questions personally and explain your recommendation clearly.",tariff_callback_button:"Book a callback",tariff_callback_avatar_alt:"Personal advice about your tariff recommendation"},
  tr:{tariff_callback_title:"Tarife önerinizle ilgili sorularınız mı var?",tariff_callback_subtitle:"Sorularınızı birebir yanıtlıyor ve önerinizi anlaşılır şekilde açıklıyoruz.",tariff_callback_button:"Geri arama randevusu al",tariff_callback_avatar_alt:"Tarife öneriniz hakkında kişisel danışmanlık"},
  ru:{tariff_callback_title:"Остались вопросы по рекомендации тарифа?",tariff_callback_subtitle:"Мы лично ответим на ваши вопросы и понятно объясним рекомендацию.",tariff_callback_button:"Записаться на звонок",tariff_callback_avatar_alt:"Персональная консультация по рекомендации тарифа"},
  ar:{tariff_callback_title:"هل لديك أسئلة حول توصية التعرفة؟",tariff_callback_subtitle:"نجيب عن أسئلتك شخصيًا ونشرح لك التوصية بوضوح.",tariff_callback_button:"حجز موعد للمكالمة",tariff_callback_avatar_alt:"استشارة شخصية حول توصية التعرفة"},
  it:{tariff_callback_title:"Hai domande sulla tariffa consigliata?",tariff_callback_subtitle:"Rispondiamo personalmente alle tue domande e ti spieghiamo la raccomandazione in modo chiaro.",tariff_callback_button:"Prenota una richiamata",tariff_callback_avatar_alt:"Consulenza personale sulla tariffa consigliata"},
  zh:{tariff_callback_title:"对推荐的资费方案还有疑问吗？",tariff_callback_subtitle:"我们会亲自解答你的问题，并清楚说明这项推荐。",tariff_callback_button:"预约回电",tariff_callback_avatar_alt:"关于资费推荐的个人咨询"},
  hi:{tariff_callback_title:"क्या आपकी सुझाई गई टैरिफ योजना के बारे में कोई सवाल है?",tariff_callback_subtitle:"हम आपके सवालों का व्यक्तिगत रूप से जवाब देंगे और आपकी सिफारिश को साफ़ और आसान भाषा में समझाएँगे।",tariff_callback_button:"कॉलबैक बुक करें",tariff_callback_avatar_alt:"आपकी टैरिफ सिफारिश पर व्यक्तिगत सलाह"},
  es:{tariff_callback_title:"¿Tienes preguntas sobre tu tarifa recomendada?",tariff_callback_subtitle:"Respondemos personalmente a tus preguntas y te explicamos la recomendación de forma clara.",tariff_callback_button:"Reservar una llamada",tariff_callback_avatar_alt:"Asesoramiento personal sobre tu tarifa recomendada"},
  fr:{tariff_callback_title:"Des questions sur votre recommandation tarifaire ?",tariff_callback_subtitle:"Nous répondons personnellement à vos questions et vous expliquons clairement votre recommandation.",tariff_callback_button:"Réserver un rappel",tariff_callback_avatar_alt:"Conseil personnalisé sur votre recommandation tarifaire"},
  nl:{tariff_callback_title:"Nog vragen over je tariefadvies?",tariff_callback_subtitle:"We beantwoorden je vragen persoonlijk en leggen je advies duidelijk uit.",tariff_callback_button:"Terugbelafspraak maken",tariff_callback_avatar_alt:"Persoonlijk advies over je tariefadvies"},
  pl:{tariff_callback_title:"Masz pytania dotyczące rekomendowanej taryfy?",tariff_callback_subtitle:"Osobiście odpowiemy na Twoje pytania i jasno wyjaśnimy rekomendację.",tariff_callback_button:"Umów rozmowę telefoniczną",tariff_callback_avatar_alt:"Osobista konsultacja dotycząca rekomendowanej taryfy"},
};
