import { fireEvent,render,screen,waitFor } from "@testing-library/react";
import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
import App from "@/App";
import { readFileSync } from "node:fs";
const key=`eyJhbGciOiJIUzI1NiJ9.${btoa(JSON.stringify({role:"anon"})).replace(/=/g,"")}.signature`;
beforeEach(()=>{vi.stubGlobal("scrollTo",vi.fn());vi.spyOn(console,"error").mockImplementation(()=>{});});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllEnvs();});
describe("booking routing and legacy removal",()=>{
 it("renders only the new callback page route",async()=>{vi.stubEnv("VITE_SUPABASE_ANON_KEY",key);vi.spyOn(globalThis,"fetch").mockImplementation(url=>Promise.resolve(new Response(String(url).includes("/rest/v1/")?"[]":JSON.stringify({calendar_name:"Rückruf buchen",calendar_slug:"rueckruf-buchen",timezone:"Europe/Berlin",duration_minutes:15,dates:[]}),{status:200})));history.replaceState({},"","/rueckruf-buchen?lang=de");render(<App/>);expect(await screen.findByRole("heading",{name:"Rückruf buchen",level:1})).toBeVisible();expect(screen.getByRole("link",{name:"Rückruf buchen"})).toHaveAttribute("href","/rueckruf-buchen?lang=de");});
 it("removes only the page hero after a successful booking",async()=>{vi.stubEnv("VITE_SUPABASE_ANON_KEY",key);const availability={calendar_name:"Rückruf buchen",calendar_slug:"rueckruf-buchen",timezone:"Europe/Berlin",duration_minutes:15,dates:[{date:"2026-08-01",start_times:["10:00"]}]};const success={booking_id:"11111111-1111-4111-8111-111111111111",calendar_name:"Rückruf buchen",calendar_slug:"rueckruf-buchen",start_at:"2026-08-01T08:00:00Z",end_at:"2026-08-01T08:15:00Z",timezone:"Europe/Berlin",duration_minutes:15,email:"ad**************",phone:"+49********123",status:"scheduled"};vi.spyOn(globalThis,"fetch").mockImplementation((_url,init)=>{const body=JSON.parse(String(init?.body||"{}"));return Promise.resolve(new Response(JSON.stringify(body.action==="book"?success:body.action==="availability"?availability:[]),{status:200}));});history.replaceState({},"","/rueckruf-buchen?lang=de");render(<App/>);fireEvent.click(await screen.findByRole("button",{name:/Aug/}));fireEvent.click(screen.getByRole("button",{name:"10:00"}));fireEvent.click(screen.getByRole("button",{name:"Weiter"}));for(const[label,value]of [["Vorname","Ada"],["Nachname","Lovelace"],["E-Mail","ada@example.test"],["Telefonnummer","123456789"]])fireEvent.change(screen.getByLabelText(label),{target:{value}});fireEvent.change(screen.getByLabelText("Anrede"),{target:{value:"Frau"}});fireEvent.click(screen.getByRole("checkbox"));fireEvent.click(screen.getByRole("button",{name:"Rückruf buchen"}));expect(await screen.findByRole("heading",{name:"Dein Rückruf ist gebucht"})).toBeVisible();expect(screen.queryByRole("heading",{name:"Rückruf buchen",level:1})).not.toBeInTheDocument();expect(screen.queryByText("Wähle einen passenden Termin. Wir rufen dich zur ausgewählten Zeit zurück.")).not.toBeInTheDocument();});
 it("lets the removed route reach NotFound without redirect",async()=>{history.replaceState({},"",`/rueckruf-${"anfordern"}?lang=de`);render(<App/>);await waitFor(()=>expect(window.location.pathname).toBe(`/rueckruf-${"anfordern"}`));expect(screen.getByText("404")).toBeVisible();});
 it("contains no legacy integration strings in website sources",()=>{for(const file of ["src/App.tsx","src/components/Footer.tsx","src/pages/RueckrufBuchen.tsx"])for(const marker of ["link."+"msgsndr","lead"+"connectorhq","z0PrnWWb"+"t0PdC4ug1Gcw"])expect(readFileSync(file,"utf8")).not.toContain(marker);});
});
