import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { afterEach, describe, expect, it, vi } from "vitest";
import { CallbackBookingWidget } from "./CallbackBookingWidget";
import { I18nProvider } from "@/lib/i18n";
import { WebsiteConfigProvider } from "@/lib/websiteConfig";
const key=`eyJhbGciOiJIUzI1NiJ9.${btoa(JSON.stringify({role:"anon"})).replace(/=/g,"")}.signature`;
const wrapper=({children}:{children:React.ReactNode})=><MemoryRouter><WebsiteConfigProvider><I18nProvider>{children}</I18nProvider></WebsiteConfigProvider></MemoryRouter>;
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllEnvs();});
describe("CallbackBookingWidget",()=>{
 it("loads mocked availability once and shows an empty state",async()=>{vi.stubEnv("VITE_SUPABASE_ANON_KEY",key);const fetchMock=vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify({dates:[]}),{status:200}));render(<CallbackBookingWidget/>,{wrapper});expect(await screen.findByText(/keine freien Termine/)).toBeInTheDocument();expect(fetchMock.mock.calls.filter(([url])=>String(url).includes("/functions/v1/booking-proxy"))).toHaveLength(1);});
 it("validates fields and books with privacy, language and source metadata",async()=>{vi.stubEnv("VITE_SUPABASE_ANON_KEY",key);let functionCalls=0;const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation(async(url)=>{if(String(url).includes("/rest/v1/"))return new Response("[]",{status:200});functionCalls++;return functionCalls===1?new Response(JSON.stringify({calendar_name:"Kromen",timezone:"Europe/Berlin",duration_minutes:30,dates:[{date:"2026-08-01",start_times:["10:00"]}]}),{status:200}):new Response(JSON.stringify({calendar_name:"Kromen",duration_minutes:30,masked_email:"a***@b.de",masked_phone:"***123",status:"confirmed"}),{status:200});});render(<CallbackBookingWidget/>,{wrapper});fireEvent.click(await screen.findByRole("button",{name:/Aug/}));fireEvent.click(screen.getByRole("button",{name:"10:00"}));fireEvent.click(screen.getByRole("button",{name:"Weiter"}));fireEvent.click(screen.getByRole("button",{name:/verbindlich/}));expect(await screen.findAllByText(/Pflichtfeld/)).not.toHaveLength(0);for(const [label,value] of [["Vorname","Ada"],["Nachname","Lovelace"],["E-Mail","ada@example.test"],["Telefonnummer","+491234567"]])fireEvent.change(screen.getByLabelText(label),{target:{value}});fireEvent.change(screen.getByLabelText("Anrede"),{target:{value:"Frau"}});fireEvent.click(screen.getByRole("checkbox"));fireEvent.click(screen.getByRole("button",{name:/verbindlich/}));expect(await screen.findByText("Dein Rückruf ist gebucht")).toBeInTheDocument();const bookingCall=fetchMock.mock.calls.filter(([url])=>String(url).includes("/functions/v1/booking-proxy"))[1];const payload=JSON.parse(String(bookingCall[1]?.body));expect(payload).toMatchObject({privacy_policy_url:"https://kromen-energieassistent.de/datenschutz",language_code:"de",source_path:"/",consent_accepted:true});expect(payload.submission_id).toBeTruthy();});
});
