import { AffiliateLayout } from "@/components/affiliate/AffiliateLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { affiliateApi } from "@/lib/affiliate-api";
import { affiliateDE as t } from "@/i18n/affiliate";
import { Copy, Gift, Link2, Share2, Users } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";

const Card = ({children,className=""}:{children:React.ReactNode;className?:string}) => <section className={`rounded-[2rem] border bg-white p-6 shadow-sm ${className}`}>{children}</section>;
const Notice = () => <div role="status" className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">{t.unavailable}</div>;

export function AffiliateLanding() { return <AffiliateLayout><section className="bg-[#f4f5f7] px-4 py-16 md:py-24"><div className="mx-auto grid max-w-6xl items-center gap-12 md:grid-cols-2"><div><p className="mb-4 font-bold text-green-700">TarifButler Empfehlungsprogramm</p><h1 className="text-4xl font-bold tracking-tight md:text-6xl">{t.title}</h1><p className="mt-6 max-w-xl text-lg text-gray-600">{t.intro}</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" className="rounded-full px-7 font-bold" asChild><Link to="/empfehlungsprogramm/registrieren">Jetzt registrieren</Link></Button><Button size="lg" variant="outline" className="rounded-full border-2 px-7 font-bold" asChild><Link to="/empfehlungsprogramm/anmelden">Anmelden</Link></Button></div></div><Card><div className="space-y-7">{[[Link2,'Link erhalten','Nach der Registrierung erhältst du deinen persönlichen Empfehlungslink.'],[Share2,'Weiterempfehlen','Teile den Link mit Menschen, für die TarifButler passen könnte.'],[Gift,'Belohnung verfolgen','Sieh transparent, welchen Status deine Empfehlungen und Belohnungen haben.']].map(([Icon,title,text],i)=><div className="flex gap-4" key={String(title)}><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-primary"><Icon /></span><div><p className="font-bold">{i+1}. {String(title)}</p><p className="text-gray-600">{String(text)}</p></div></div>)}</div></Card></div></section></AffiliateLayout> }

type AuthKind='anmelden'|'registrieren'|'passwort-vergessen'|'passwort-zuruecksetzen'|'aktivieren';
export function AffiliateAuth({kind}:{kind:AuthKind}) { const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [isError,setIsError]=useState(false); const location=useLocation(); const navigate=useNavigate(); const token=new URLSearchParams(location.search).get('token'); const invalid=!token && (kind==='aktivieren'||kind==='passwort-zuruecksetzen');
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setMessage('');setIsError(false);const data=new FormData(e.currentTarget);if(kind==='registrieren'&&data.get('password')!==data.get('confirmation')){setIsError(true);setMessage('Die Passwörter stimmen nicht überein.');return}setBusy(true);try { if(kind==='anmelden'){await affiliateApi.login(String(data.get('email')),String(data.get('password')));navigate('/empfehlungsprogramm/portal',{replace:true});return}if(kind==='registrieren'){await affiliateApi.register({name:String(data.get('name')),email:String(data.get('email')),password:String(data.get('password'))});setMessage('Dein Konto wurde erstellt. Bitte prüfe dein E-Mail-Postfach, um die Registrierung zu bestätigen.')}else if(kind==='passwort-vergessen'){await affiliateApi.forgotPassword(String(data.get('email')));setMessage('Falls ein Konto zu dieser E-Mail-Adresse besteht, erhältst du weitere Anweisungen per E-Mail.')}else{await affiliateApi.resetPassword(token||'',String(data.get('password')));setMessage('Dein Passwort wurde erfolgreich geändert. Du kannst dich jetzt anmelden.')}}catch{setIsError(true);setMessage(t.unavailable)}finally{setBusy(false)}};
 const titles={anmelden:'Willkommen zurück',registrieren:'Empfehlungsprogramm starten','passwort-vergessen':'Passwort vergessen','passwort-zuruecksetzen':'Neues Passwort festlegen',aktivieren:'Konto aktivieren'};
 return <AffiliateLayout><div className="mx-auto max-w-lg px-4 py-16"><Card><h1 className="text-3xl font-bold">{titles[kind]}</h1><p className="mb-7 mt-2 text-gray-600">Sicher über TarifButler anmelden und Empfehlungen verwalten.</p>{kind==='aktivieren'&&!invalid ? <NoticeText text="Der Aktivierungslink liegt vor. Die Kontoaktivierung ist derzeit noch nicht verfügbar und wurde nicht bestätigt."/>:invalid?<><Notice/><p className="mt-4 text-sm">Der Link fehlt, ist ungültig oder abgelaufen. Fordere bei Bedarf einen neuen Link an.</p></>:<form className="space-y-4" onSubmit={submit}>{kind==='registrieren'&&<Field name="name" label="Name" autoComplete="name"/>}{kind!=='passwort-zuruecksetzen'&&<Field name="email" label="E-Mail-Adresse" type="email" autoComplete="email"/>}{kind!=='passwort-vergessen'&&<Field name="password" label="Passwort" type="password" autoComplete={kind==='anmelden'?'current-password':'new-password'}/>} {kind==='registrieren'&&<><Field name="confirmation" label="Passwort bestätigen" type="password" autoComplete="new-password"/><label className="flex gap-3 text-sm"><input required type="checkbox"/> <span>Ich akzeptiere die Programmbedingungen und habe die Datenschutzhinweise gelesen.</span></label></>}<Button disabled={busy} className="w-full rounded-full font-bold" type="submit">{busy?'Wird gesendet …':kind==='anmelden'?'Anmelden':'Anfrage senden'}</Button>{message&&<div role={isError?'alert':'status'}><NoticeText text={message} error={isError}/></div>}</form>}<div className="mt-6 flex flex-wrap justify-between gap-3 text-sm underline">{kind==='anmelden'&&<Link to="/empfehlungsprogramm/passwort-vergessen">Passwort vergessen?</Link>}<Link to={kind==='registrieren'?'/empfehlungsprogramm/anmelden':'/empfehlungsprogramm/registrieren'}>{kind==='registrieren'?'Bereits registriert?':'Noch nicht registriert?'}</Link></div></Card></div></AffiliateLayout> }
function Field({label,...props}:{label:string;name:string;type?:string;autoComplete?:string}){return <label className="block text-sm font-semibold">{label}<Input required className="mt-2 h-12 rounded-2xl" {...props}/></label>};
function NoticeText({text,error=false}:{text:string;error?:boolean}){return <div className={`rounded-2xl p-4 text-sm ${error?'border border-red-200 bg-red-50 text-red-900':'bg-[#f4f5f7]'}`}>{text}</div>}

export function AffiliatePortal(){const {section='portal'}=useParams();return <AffiliateLayout portal><div className="mx-auto max-w-6xl px-4 py-10"><PortalSection section={section}/></div></AffiliateLayout>}
function PortalSection({section}:{section:string}) { if(section==='empfehlungen') return <><Heading title="Empfehlungen" text="Status deiner geteilten Empfehlungen – mit bewusst minimalen personenbezogenen Daten."/><Notice/><Empty title="Noch keine Empfehlungen" text="Sobald der Service verfügbar ist, erscheinen Name oder Initialen, Datum, Prozessstatus und Belohnung hier."/></>; if(section==='belohnungen') return <><Heading title="Belohnungen" text="Nachvollziehbare Belohnungen mit dem zum Abschlusszeitpunkt gespeicherten Programmsnapshot."/><Notice/><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Ausstehend','pending'],['Auszahlbar','available'],['Ausgezahlt','paid'],['Storniert','cancelled']].map(([a,b])=><Card key={b}><p className="text-sm text-gray-500">{a}</p><p className="mt-2 text-2xl font-bold">—</p><p className="mt-2 text-xs uppercase tracking-wide">{b}</p></Card>)}</div><Empty title="Keine Belohnungen vorhanden" text="Betrag, Status, Stichtag und unveränderter Programmsnapshot werden künftig hier angezeigt."/></>; if(section==='profil') return <><Heading title="Profil" text="Verwalte Konto, Sicherheit und Auszahlungseinstellungen."/><Notice/><div className="mt-6 grid gap-5 md:grid-cols-2"><Card><h2 className="text-xl font-bold">Konto & Profil</h2><p className="my-4 text-gray-600">Name und E-Mail-Adresse werden nach Verfügbarkeit sicher geladen.</p><Button disabled variant="outline">Profil bearbeiten</Button></Card><Card><h2 className="text-xl font-bold">Sicherheit</h2><p className="my-4 text-gray-600">Passwort sicher über den Kontodienst ändern.</p><Button disabled variant="outline">Passwort ändern</Button></Card><Card className="md:col-span-2"><h2 className="text-xl font-bold">Auszahlungsmethode</h2><p className="mt-4 text-gray-600">Noch nicht hinterlegt · Eine IBAN wird ausschließlich maskiert angezeigt, z. B. DE•• •••• •••• 1234.</p></Card></div></>;
 return <><Heading title="Hallo!" text="Hier findest du dein Empfehlungsprogramm auf einen Blick."/><Notice/><div className="mt-6 grid gap-5 md:grid-cols-3"><Card className="md:col-span-2"><p className="text-sm font-semibold text-gray-500">AKTUELLES PROGRAMM</p><h2 className="mt-2 text-2xl font-bold">Programmdetails werden geladen</h2><p className="mt-2 text-gray-600">Belohnungen richten sich nach den jeweils gültigen Bedingungen und sind nicht garantiert.</p></Card><Card><p className="text-sm font-semibold text-gray-500">DEIN EMPFEHLUNGSLINK</p><p className="my-3 truncate font-mono">Noch nicht verfügbar</p><div className="flex gap-2"><Button disabled variant="outline"><Copy/> Kopieren</Button><Button disabled variant="outline"><Share2/> Teilen</Button></div></Card></div><div className="mt-5 grid grid-cols-2 gap-4 lg:grid-cols-4">{['Link-Klicks','Tarifempfehlungen','Abschlüsse','Bestätigte Abschlüsse'].map(x=><Card key={x}><p className="text-sm text-gray-500">{x}</p><p className="mt-2 text-3xl font-bold">—</p></Card>)}</div><div className="mt-5 grid gap-4 md:grid-cols-3">{['Ausstehend','Auszahlbar','Ausgezahlt'].map(x=><Card key={x}><p className="text-sm text-gray-500">{x}</p><p className="mt-2 text-2xl font-bold">— €</p></Card>)}</div></> }
function Heading({title,text}:{title:string;text:string}){return <header className="mb-7"><h1 className="text-3xl font-bold md:text-4xl">{title}</h1><p className="mt-2 text-gray-600">{text}</p></header>};
function Empty({title,text}:{title:string;text:string}){return <Card className="mt-6 text-center"><Users className="mx-auto mb-3 h-10 w-10 text-gray-400"/><h2 className="font-bold">{title}</h2><p className="mx-auto mt-2 max-w-lg text-sm text-gray-600">{text}</p></Card>}
