import { AffiliateLayout } from "@/components/affiliate/AffiliateLayout";
import { HowItWorks, type HowItWorksStep } from "@/components/HowItWorks";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { AffiliateApiError, affiliateApi, type AffiliateOverview, type AffiliatePayout, type AffiliatePayoutMethod, type AffiliateProfile, type AffiliateReferral, type AffiliateReward } from "@/lib/affiliate-api";
import { affiliateDE as t } from "@/i18n/affiliate";
import { affiliateDestination, safeAffiliateSearch } from "@/lib/affiliate-navigation";
import { Check, CheckCircle2, Copy, Gift, Link2, Share2, Sparkles, Users } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";

const Card = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => <section className={`rounded-[2rem] border bg-white p-6 shadow-sm ${className}`}>{children}</section>;
const Notice = ({ children = t.unavailable, error = false }: { children?: React.ReactNode; error?: boolean }) => <div role={error ? "alert" : "status"} className={`rounded-2xl border p-4 text-sm ${error ? "border-red-200 bg-red-50 text-red-900" : "border-amber-200 bg-amber-50 text-amber-950"}`}>{children}</div>;

export function AffiliateLanding() {
  const { search } = useLocation();
  const register = affiliateDestination("/empfehlungsprogramm/registrieren", search);
  useEffect(() => {
    window.scrollTo({ top: 0, left: 0 });
  }, []);
  const steps = [
    [Link2, "Registrieren und Link erhalten", "Nach der Registrierung findest du deinen persönlichen Empfehlungslink direkt in deinem TarifButler Empfehlungsportal."],
    [Share2, "Link teilen", "Teile deinen Link mit Freunden, Familie oder Bekannten – zum Beispiel per WhatsApp, Social Media oder einfach direkt."],
    [Gift, "Belohnung erhalten", "Eine Belohnung entsteht, wenn die empfohlene Person den Tarif abschließt und der neue Energieanbieter den Auftrag erfolgreich bestätigt."],
  ] as const;
  const howItWorksSteps: HowItWorksStep[] = steps.map(([, title, description], index) => ({ id: index + 1, num: String(index + 1), title, description }));
  return <AffiliateLayout><>
    <section className="w-full overflow-hidden bg-white pb-24 pt-12 lg:pb-32 lg:pt-24"><div className="container mx-auto px-4 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-4xl flex-col items-center text-center"><p className="mb-8 inline-flex items-center rounded-full border border-border/50 px-4 py-2 text-sm font-semibold text-foreground"><span className="mr-3 h-3 w-3 rounded-full bg-[#42f77a]" />TarifButler Empfehlungsprogramm</p><h1 className="text-4xl font-extrabold leading-[1.1] tracking-tight text-foreground sm:text-5xl lg:text-6xl xl:text-7xl">Empfehlen lohnt sich.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-muted-foreground">Hilf Freunden, Familie oder Bekannten dabei, ihren Strom- oder Gastarif kostenlos und unverbindlich prüfen zu lassen. Wird aus deiner Empfehlung ein erfolgreich bestätigter Anbieterwechsel, erhältst du eine Belohnung als Dankeschön.</p><RegistrationButton to={register} className="mt-10" /><p className="mt-3 text-sm italic text-muted-foreground">Bereits registriert? <Link className="font-semibold underline" to={affiliateDestination("/empfehlungsprogramm/anmelden", search)}>Anmelden</Link></p></div></div></section>
    <HowItWorks steps={howItWorksSteps} />
    <section className="bg-white py-24"><div className="container mx-auto max-w-6xl px-4"><h2 className="mb-16 text-center text-4xl font-bold leading-tight text-[#0b1221] md:text-5xl">Du empfiehlst.<br />Wir kümmern uns um den Rest.</h2><div className="grid gap-12 md:grid-cols-2">{[[Share2, "Einfach deinen Link teilen", "Du musst niemandem Tarife erklären oder selbst Angebote vergleichen. Du teilst einfach deinen persönlichen Empfehlungslink."], [Sparkles, "TarifButler übernimmt", "Wir prüfen die Tarife, analysieren die passenden Möglichkeiten und begleiten die empfohlene Person durch den weiteren Prozess."]].map(([Icon, title, text]) => <div key={String(title)}><div className="mb-4 flex items-center gap-3"><Icon className="h-8 w-8 shrink-0 text-[#42f77a]" /><h3 className="text-2xl font-bold text-[#0b1221]">{String(title)}</h3></div><p className="text-lg leading-relaxed text-slate-700">{String(text)}</p></div>)}</div></div></section>
    <section className="bg-[#42f77a] py-12 md:py-24"><div className="container mx-auto max-w-5xl px-4 text-center"><h2 className="text-3xl font-extrabold leading-tight tracking-tight text-[#0b1221] md:text-5xl">Mehr Empfehlungen. Mehr Belohnungen.</h2><p className="mx-auto mt-6 max-w-3xl text-lg font-medium text-[#0b1221] md:text-xl">Jede erfolgreich bestätigte Empfehlung zählt. Deinen persönlichen Empfehlungslink kannst du beliebig oft teilen.</p><RegistrationButton to={register} className="mt-10 bg-white hover:bg-white/90" /></div></section>
    <section className="bg-white py-24"><div className="container mx-auto max-w-6xl px-4"><div className="mb-16 text-center"><h2 className="text-4xl font-extrabold leading-tight text-[#0b1221] md:text-5xl">Wann gilt eine Empfehlung als erfolgreich?</h2><p className="mx-auto mt-6 max-w-3xl text-lg leading-relaxed text-slate-700">Eine Empfehlung kann zugeordnet werden, wenn eine Person über deinen persönlichen Empfehlungslink zu TarifButler kommt und den Tarifprozess startet.</p></div><div className="grid gap-6 md:grid-cols-2"><div className="rounded-[2rem] bg-[#42f77a] p-8 md:p-12"><h3 className="mb-8 text-2xl font-bold text-[#0b1221] md:text-3xl">Eine Belohnung entsteht, wenn:</h3><ul className="space-y-6">{["die empfohlene Person den empfohlenen Tarif tatsächlich abschließt", "der neue Energieanbieter den Auftrag erfolgreich bestätigt"].map(item => <li className="flex items-start gap-4 text-lg leading-relaxed text-[#0b1221]" key={item}><Check className="mt-1 h-6 w-6 shrink-0" strokeWidth={3} />{item}</li>)}</ul></div><div className="rounded-[2rem] border-2 border-[#0b1221]/10 bg-white p-8 md:p-12"><CheckCircle2 className="mb-6 h-10 w-10 text-[#42f77a]" /><h3 className="text-2xl font-bold text-[#0b1221] md:text-3xl">Bestätigt statt nur geklickt</h3><p className="mt-6 text-lg leading-relaxed text-slate-700">Ein Klick auf deinen Link oder der Start der Tarifprüfung allein löst noch keine Belohnung aus.</p><p className="mt-4 text-lg leading-relaxed text-slate-700">Kommt kein Vertrag zustande oder bestätigt der Anbieter den Auftrag nicht, entsteht keine Belohnung.</p></div></div></div></section>
    <section className="bg-white px-4 py-12"><div className="mx-auto flex min-h-[360px] max-w-6xl items-center justify-center overflow-hidden rounded-[2rem] bg-[#0b1221] px-6 py-16 text-center text-white shadow-lg"><div className="max-w-4xl"><h2 className="text-4xl font-extrabold leading-tight md:text-5xl">Gemeinsam weniger für Energie zahlen.</h2><p className="mx-auto mt-6 max-w-3xl text-lg leading-relaxed text-gray-300 md:text-xl">Viele Menschen wissen nicht, ob ihr aktueller Strom- oder Gastarif noch zu ihrer Situation passt. Mit deiner Empfehlung gibst du ihnen einen einfachen Weg, das kostenlos herauszufinden.</p><p className="mt-5 text-lg font-semibold">Du teilst den Link. Wir übernehmen die Prüfung. Und eine erfolgreiche Empfehlung lohnt sich auch für dich.</p><RegistrationButton to={register} className="mt-10" /></div></div></section>
  </></AffiliateLayout>;
}

function RegistrationButton({ to, className = "" }: { to: string; className?: string }) { return <Button className={`rounded-full bg-[#42f77a] px-10 py-7 text-lg font-bold text-[#0b1221] shadow-lg transition-transform hover:scale-105 hover:bg-[#42f77a]/90 ${className}`} size="lg" asChild><Link to={to}>Registrieren</Link></Button>; }

type AuthKind = "anmelden" | "registrieren" | "passwort-vergessen" | "passwort-zuruecksetzen" | "aktivieren";
export function AffiliateAuth({ kind }: { kind: AuthKind }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [isError, setIsError] = useState(false); const [tokenConsumed, setTokenConsumed] = useState(false);
  const location = useLocation(); const navigate = useNavigate(); const query = new URLSearchParams(location.search); const token = query.get("token");
  const invalid = !token && !tokenConsumed && (kind === "aktivieren" || kind === "passwort-zuruecksetzen");
  const removeSecretsFromAddress = useCallback(() => navigate(`${location.pathname}${safeAffiliateSearch(location.search)}${location.hash}`, { replace: true }), [location.hash, location.pathname, location.search, navigate]);
  useEffect(() => { if (kind !== "aktivieren" || !token || tokenConsumed) return; let active = true; setBusy(true); setMessage(""); setIsError(false); affiliateApi.activate(token).then(() => { if (active) { setTokenConsumed(true); setMessage("Dein Konto wurde aktiviert. Du kannst dich jetzt anmelden."); setBusy(false); removeSecretsFromAddress(); } }).catch(() => { if (active) { setIsError(true); setMessage(t.unavailable); setBusy(false); } }); return () => { active = false; }; }, [kind, removeSecretsFromAddress, token, tokenConsumed]);
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setMessage(""); setIsError(false); const data = new FormData(event.currentTarget);
    if ((kind === "registrieren" || kind === "passwort-zuruecksetzen") && data.get("password") !== data.get("confirmation")) { setIsError(true); setMessage("Die Passwörter stimmen nicht überein."); return; }
    setBusy(true);
    try {
      if (kind === "anmelden") { await affiliateApi.login(String(data.get("email")), String(data.get("password"))); navigate(affiliateDestination("/empfehlungsprogramm/portal", location.search), { replace: true }); return; }
      if (kind === "registrieren") { const inviteToken = query.get("inviteToken")?.trim(); await affiliateApi.register({ name: String(data.get("name")), email: String(data.get("email")), password: String(data.get("password")), ...(inviteToken ? { inviteToken } : {}) }); const session = await affiliateApi.session(); if (session.authenticated && session.user) { navigate(affiliateDestination("/empfehlungsprogramm/portal", location.search), { replace: true }); return; } setMessage("Dein Konto wurde erstellt. Bitte prüfe dein E-Mail-Postfach, um die Registrierung zu bestätigen."); removeSecretsFromAddress(); }
      else if (kind === "passwort-vergessen") { await affiliateApi.forgotPassword(String(data.get("email"))); setMessage("Falls ein Konto zu dieser E-Mail-Adresse besteht, erhältst du weitere Anweisungen per E-Mail."); }
      else { await affiliateApi.resetPassword(token || "", String(data.get("password"))); setTokenConsumed(true); setMessage("Dein Passwort wurde erfolgreich geändert. Du kannst dich jetzt anmelden."); removeSecretsFromAddress(); }
    } catch { setIsError(true); setMessage(t.unavailable); } finally { setBusy(false); }
  };
  const titles = { anmelden: "Willkommen zurück", registrieren: "Registrieren", "passwort-vergessen": "Passwort vergessen", "passwort-zuruecksetzen": "Neues Passwort festlegen", aktivieren: "Konto aktivieren" };
  const buttonText = kind === "anmelden" ? "Anmelden" : kind === "registrieren" ? "Registrieren" : kind === "passwort-vergessen" ? "Link anfordern" : "Passwort speichern";
  return <AffiliateLayout kind="auth"><div className="mx-auto max-w-lg px-4 py-10 md:py-16"><Card><h1 className="mb-7 text-3xl font-bold">{titles[kind]}</h1>{kind === "passwort-vergessen" && <p className="mb-7 -mt-4 text-gray-600">Wir senden dir einen Link an deine E-Mail-Adresse, mit dem du dein Passwort sicher neu festlegen kannst.</p>}{kind === "aktivieren" && !invalid ? <Notice error={isError}>{busy || !message ? "Dein Konto wird aktiviert …" : message}</Notice> : invalid ? <><Notice /><p className="mt-4 text-sm">Der Link fehlt, ist ungültig oder abgelaufen. Fordere bei Bedarf einen neuen Link an.</p></> : <form className="space-y-4" onSubmit={submit}>{kind === "registrieren" && <Field name="name" label="Name" autoComplete="name" />}{kind !== "passwort-zuruecksetzen" && <Field name="email" label="E-Mail-Adresse" type="email" autoComplete="email" />}{kind !== "passwort-vergessen" && <Field name="password" label={kind === "passwort-zuruecksetzen" ? "Neues Passwort" : "Passwort"} type="password" autoComplete={kind === "anmelden" ? "current-password" : "new-password"} />}{(kind === "registrieren" || kind === "passwort-zuruecksetzen") && <Field name="confirmation" label={kind === "passwort-zuruecksetzen" ? "Neues Passwort bestätigen" : "Passwort bestätigen"} type="password" autoComplete="new-password" />}{kind === "registrieren" && <label className="flex gap-3 text-sm"><input required type="checkbox" /> <span>Ich akzeptiere die Programmbedingungen und habe die Datenschutzhinweise gelesen.</span></label>}<Button disabled={busy} className="w-full rounded-full font-bold" type="submit">{busy ? "Wird gesendet …" : buttonText}</Button>{message && <Notice error={isError}>{message}</Notice>}</form>}<div className="mt-6 flex flex-wrap justify-between gap-3 text-sm underline">{kind === "anmelden" && <Link to={affiliateDestination("/empfehlungsprogramm/passwort-vergessen", location.search)}>Passwort vergessen?</Link>}<Link to={affiliateDestination(kind === "registrieren" ? "/empfehlungsprogramm/anmelden" : "/empfehlungsprogramm/registrieren", location.search)}>{kind === "registrieren" ? "Bereits registriert?" : "Noch nicht registriert?"}</Link></div></Card></div></AffiliateLayout>;
}
function Field({ label, ...props }: { label: string; name: string; type?: string; autoComplete?: string }) { return <label className="block text-sm font-semibold">{label}<Input required className="mt-2 h-12 rounded-2xl" {...props} /></label>; }

type PortalData = AffiliateOverview | AffiliateReferral[] | AffiliateReward[] | { profile: AffiliateProfile; payouts: AffiliatePayout[]; payoutMethod: AffiliatePayoutMethod | null };
type PortalSectionName = "portal" | "empfehlungen" | "belohnungen" | "profil";
type PortalState = { section: PortalSectionName; status: "loading" | "ready" | "empty" | "error"; data?: PortalData; userName?: string };
export function AffiliatePortal({ section }: { section: "portal" | "empfehlungen" | "belohnungen" | "profil" }) {
  const navigate = useNavigate(); const location = useLocation(); const [state, setState] = useState<PortalState>({ section, status: "loading" });
  useEffect(() => { let active = true; const load = async () => {
    setState({ section, status: "loading" });
    try {
      const session = await affiliateApi.session();
      if (!session.authenticated || !session.user) { navigate(affiliateDestination("/empfehlungsprogramm/anmelden", location.search), { replace: true }); return; }
      await affiliateApi.bootstrapProfile();
      let data: PortalData;
      if (section === "empfehlungen") data = await affiliateApi.referrals();
      else if (section === "belohnungen") data = await affiliateApi.rewards();
      else if (section === "profil") { const [profile, payouts, payoutMethod] = await Promise.all([affiliateApi.profile(), affiliateApi.payouts(), affiliateApi.payoutMethod()]); data = { profile, payouts, payoutMethod }; }
      else data = await affiliateApi.overview();
      const empty = Array.isArray(data) && data.length === 0;
      if (active) setState({ section, status: empty ? "empty" : "ready", data, userName: session.user.name });
    } catch (error) {
      if (error instanceof AffiliateApiError && (error.status === 401 || error.status === 403)) { navigate(affiliateDestination("/empfehlungsprogramm/anmelden", location.search), { replace: true }); return; }
      if (active) setState({ section, status: "error" });
    }
  }; void load(); return () => { active = false; }; }, [location.search, navigate, section]);
  const logout = async () => { try { await affiliateApi.logout(); } finally { navigate(affiliateDestination("/empfehlungsprogramm/anmelden", location.search), { replace: true }); } };
  const currentState = state.section === section ? state : { section, status: "loading" as const };
  return <AffiliateLayout kind="portal" onLogout={logout}><div className="mx-auto max-w-6xl px-4 py-10">{currentState.status === "loading" ? <Notice>Portal wird geladen …</Notice> : currentState.status === "error" ? <Notice error /> : <PortalSection section={section} state={currentState} />}</div></AffiliateLayout>;
}

function PortalSection({ section, state }: { section: string; state: PortalState }) {
  if (section === "empfehlungen") { const rows = (state.data || []) as AffiliateReferral[]; return <><Heading title="Deine Empfehlungen" text="Hier siehst du, welche Empfehlungen über deinen persönlichen Link zugeordnet wurden und welchen aktuellen Status sie haben." />{rows.length === 0 ? <Empty title="Noch keine Empfehlungen" text="Neue Empfehlungen erscheinen hier, sobald sie vorliegen." /> : <div className="space-y-3">{rows.map(row => <Card key={row.id}><p className="font-bold">Empfehlung</p><p className="text-sm text-gray-600">{row.status}{row.attributedAt ? ` · ${formatDate(row.attributedAt)}` : ""}</p></Card>)}</div>}</>; }
  if (section === "belohnungen") { const rows = (state.data || []) as AffiliateReward[]; return <><Heading title="Deine Belohnungen" text="Sobald eine Empfehlung die Voraussetzungen für eine Belohnung erfüllt, kannst du den Status hier nachvollziehen." />{rows.length === 0 ? <Empty title="Keine Belohnungen vorhanden" text="Belohnungen erscheinen hier, sobald sie vorliegen." /> : <div className="space-y-3">{rows.map(row => <Card key={row.id}><p className="font-bold">{money(row.amount, row.currency)}</p><p className="text-sm text-gray-600">{row.status}{row.voucherLabel ? ` · ${row.voucherLabel}` : ""}</p></Card>)}</div>}</>; }
  if (section === "profil") { const data = state.data as { profile: AffiliateProfile; payouts: AffiliatePayout[]; payoutMethod: AffiliatePayoutMethod | null }; return <><Heading title="Einstellungen" text="Verwalte deine Kontodaten, dein Passwort und deine Auszahlungseinstellungen." /><div className="grid gap-5 md:grid-cols-2"><Card><h2 className="text-xl font-bold">Konto & Profil</h2><p className="mt-4">{data.profile.firstName} {data.profile.lastName}</p><p className="text-gray-600">Mitglied seit {formatDate(data.profile.memberSince)} · {data.profile.status}</p></Card><PasswordChange /><Card><h2 className="text-xl font-bold">Auszahlungsmethode</h2><p className="mt-4 text-gray-600">{safeMaskedIban(data.payoutMethod?.maskedIban || undefined) || "Noch nicht hinterlegt"}</p></Card><Card><h2 className="text-xl font-bold">Auszahlungen</h2>{data.payouts.length ? data.payouts.map(item => <p key={item.id} className="mt-3">{money(item.amount, item.currency)} · {item.status}</p>) : <p className="mt-4 text-gray-600">Noch keine Auszahlungen.</p>}</Card></div></>; }
  const data = state.data as AffiliateOverview; return <><Heading title={`Hallo ${state.userName || ""}`.trim()} text="Hier findest du deinen persönlichen Empfehlungslink und behältst deine Empfehlungen und Belohnungen im Blick." /><div className="grid gap-5 md:grid-cols-3"><Card className="md:col-span-2"><h2 className="text-xl font-bold">Dein persönlicher Empfehlungslink</h2><p className="mt-2 text-sm text-gray-600">Teile diesen Link mit Freunden, Familie oder Bekannten. Empfehlungen über diesen Link werden automatisch deinem Konto zugeordnet.</p><p className="my-4 break-all font-mono">{data.referralUrl || "Noch nicht verfügbar"}</p><div className="flex flex-wrap gap-3"><Button disabled={!data.referralUrl} variant="outline" onClick={() => data.referralUrl && navigator.clipboard.writeText(data.referralUrl)}><Copy /> Kopieren</Button>{data.referralUrl && <Button variant="outline" asChild><a href={`https://wa.me/?text=${encodeURIComponent(data.referralUrl)}`} target="_blank" rel="noreferrer"><Share2 /> Über WhatsApp teilen</a></Button>}</div></Card></div><div className="mt-5 grid gap-4 md:grid-cols-3">{[["Empfehlungen", data.totals.referrals], ["Verfügbare Belohnungen", data.totals.availableRewards], ["Ausgezahlte Belohnungen", data.totals.paidRewards]].map(([label, value]) => <Card key={String(label)}><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-3xl font-bold">{typeof value === "number" ? value : "—"}</p></Card>)}</div></>;
}

function PasswordChange() { const [status, setStatus] = useState(""); const [error, setError] = useState(false); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setStatus(""); setError(false); const form = new FormData(event.currentTarget); if (form.get("newPassword") !== form.get("confirmation")) { setError(true); setStatus("Die Passwörter stimmen nicht überein."); return; } try { await affiliateApi.changePassword(String(form.get("currentPassword")), String(form.get("newPassword"))); setStatus("Dein Passwort wurde erfolgreich geändert."); event.currentTarget.reset(); } catch { setError(true); setStatus(t.unavailable); } }; return <Card><h2 className="text-xl font-bold">Sicherheit</h2><form className="mt-4 space-y-3" onSubmit={submit}><Field name="currentPassword" label="Aktuelles Passwort" type="password" autoComplete="current-password" /><Field name="newPassword" label="Neues Passwort" type="password" autoComplete="new-password" /><Field name="confirmation" label="Neues Passwort bestätigen" type="password" autoComplete="new-password" /><Button type="submit" variant="outline">Passwort ändern</Button>{status && <Notice error={error}>{status}</Notice>}</form></Card>; }
function Heading({ title, text }: { title: string; text: string }) { return <header className="mb-7"><h1 className="text-3xl font-bold md:text-4xl">{title}</h1><p className="mt-2 text-gray-600">{text}</p></header>; }
function Empty({ title, text }: { title: string; text: string }) { return <Card className="mt-6 text-center"><Users className="mx-auto mb-3 h-10 w-10 text-gray-400" /><h2 className="font-bold">{title}</h2><p className="mx-auto mt-2 max-w-lg text-sm text-gray-600">{text}</p></Card>; }
const money = (amount?: number, currency = "EUR") => typeof amount === "number" ? new Intl.NumberFormat("de-DE", { style: "currency", currency }).format(amount) : "—";
const formatDate = (value: string) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : new Intl.DateTimeFormat("de-DE").format(date); };
const safeMaskedIban = (value?: string) => value && /^[A-Z]{2}[•*Xx\s\d-]{6,34}$/.test(value) && /[•*Xx]/.test(value) ? value : undefined;
