import { fireEvent,render,screen,waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { afterEach,describe,expect,it,vi } from "vitest";
import Tarif from "@/pages/Tarif";
import { I18nProvider,LANGUAGES,useI18n } from "@/lib/i18n";
import { tariffCallbackTranslations } from "@/lib/tariffCallbackI18n";
import { WebsiteConfigProvider } from "@/lib/websiteConfig";

const TranslationProbe=()=>{const{t}=useI18n();return <><span data-testid="footer-callback">{t("footer_callback")}</span><span data-testid="callback-title">{t("callback_title")}</span></>};

const wrapper=({children,lang="de"}:{children:React.ReactNode;lang?:string})=><MemoryRouter initialEntries={[`/tarif?lang=${lang}`]}><WebsiteConfigProvider><I18nProvider>{children}</I18nProvider></WebsiteConfigProvider></MemoryRouter>;
afterEach(()=>{vi.restoreAllMocks();document.documentElement.dir="ltr";});

describe("TarifCallbackSection",()=>{
 it("renders between the existing offer iframe and footer with configured avatar",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response("[]",{status:200}));const{container}=render(wrapper({children:<Tarif/>}));const iframe=screen.getByTitle("Angebotsseite Loader");const section=await screen.findByTestId("tarif-callback-section");const footer=container.querySelector("footer")!;expect(iframe.compareDocumentPosition(section)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(section.compareDocumentPosition(footer)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(screen.getByRole("heading",{name:"Noch Fragen zu deiner Tarifempfehlung?"})).toBeVisible();expect(screen.getByRole("link",{name:"Rückruf buchen"})).toHaveAttribute("href","/rueckruf-buchen?lang=de");expect(screen.getByRole("img",{name:/Marvin Ehiogie/})).toHaveAttribute("src",expect.stringContaining("69d3fc76bc1d4a17f7def171"));});
 it("shows a neutral fixed-size fallback when the configured avatar fails",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response("[]",{status:200}));render(wrapper({children:<Tarif/>}));const avatar=await screen.findByRole("img",{name:/Marvin Ehiogie/});fireEvent.error(avatar);const fallback=screen.getByRole("img",{name:/Persönliche Beratung/});expect(fallback).toBeVisible();expect(fallback.tagName).toBe("DIV");});
 it("preserves Arabic language and RTL navigation",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response("[]",{status:200}));render(wrapper({children:<Tarif/>,lang:"ar"}));expect(await screen.findByRole("heading",{name:"هل لديك أسئلة حول توصية التعرفة؟"})).toBeVisible();expect(screen.getByRole("link",{name:"حجز موعد للمكالمة"})).toHaveAttribute("href","/rueckruf-buchen?lang=ar");await waitFor(()=>expect(document.documentElement.dir).toBe("rtl"));});
 it("uses consistent Hindi callback terminology outside the booking widget",async()=>{render(wrapper({children:<TranslationProbe/>,lang:"hi"}));expect(await screen.findByTestId("footer-callback")).toHaveTextContent("कॉलबैक बुक करें");expect(screen.getByTestId("callback-title")).toHaveTextContent("कॉलबैक बुक करें");expect(tariffCallbackTranslations.hi.tariff_callback_button).toBe("कॉलबैक बुक करें");const texts=[screen.getByTestId("footer-callback").textContent,screen.getByTestId("callback-title").textContent,...Object.values(tariffCallbackTranslations.hi)].join(" ");expect(texts).not.toContain("वापसी कॉल");expect(texts).not.toContain("कॉल बैक");});
 it("uses the approved Polish callback terminology",()=>{expect(tariffCallbackTranslations.pl.tariff_callback_button).toBe("Umów rozmowę telefoniczną");expect(Object.values(tariffCallbackTranslations.pl).join(" ").toLocaleLowerCase("pl")).not.toContain("rozmowa zwrotna");});
 it("uses consistent Arabic appointment terminology and keeps RTL",async()=>{render(wrapper({children:<TranslationProbe/>,lang:"ar"}));expect(await screen.findByTestId("footer-callback")).toHaveTextContent("حجز موعد للمكالمة");expect(screen.getByTestId("callback-title")).toHaveTextContent("حجز موعد للمكالمة");expect(tariffCallbackTranslations.ar.tariff_callback_button).toBe("حجز موعد للمكالمة");await waitFor(()=>expect(document.documentElement.dir).toBe("rtl"));});
 it("keeps complete, non-empty tariff CTA translations and unchanged German copy",()=>{expect(Object.keys(tariffCallbackTranslations)).toEqual(LANGUAGES.map(({code})=>code));for(const{code}of LANGUAGES){expect(Object.keys(tariffCallbackTranslations[code]).sort()).toEqual(["tariff_callback_avatar_alt","tariff_callback_button","tariff_callback_subtitle","tariff_callback_title"]);expect(Object.values(tariffCallbackTranslations[code]).every(value=>value.trim().length>0)).toBe(true);}expect(tariffCallbackTranslations.de).toEqual({tariff_callback_title:"Noch Fragen zu deiner Tarifempfehlung?",tariff_callback_subtitle:"Wir beantworten deine Fragen persönlich und erklären dir deine Empfehlung verständlich.",tariff_callback_button:"Rückruf buchen",tariff_callback_avatar_alt:"Persönliche Beratung zu deiner Tarifempfehlung"});});
});
